### ISSUE TITLE
About full sort 

### ISSUE THREAD

**Issue by FelixHilyer** [Woeee/FMLP-Rec#1]
Hi, thanks for your great work!
But I have a question.  I noticed that when using the parameter full sort, you use full items in validation and testing. Have you tried using the full sort during training as well, and how does it compare to that?
Looking forward to your reply！

**Comment by Woeee** [comment]
Thanks for your praise
If you choose full sort, in every epoch of training, the model will be evaluated using all items, which also decide the time to quit training. 
I hope my reply will help you.
