### ISSUE TITLE
采用full sort时的模型参数

### ISSUE THREAD

**Issue by FelixHilyer** [Woeee/FMLP-Rec#2]
您好！
我们在对模型采用full sort参数时，尝试了一些超参数，得到的结果都与您在论文附录中提供的数据相差较大。请问您能给出当采用full sort时，FMLP模型在几个数据集上的超参吗？
期待您的回复。

**Comment by Woeee** [comment]
您好！
我们采用full sort进行评价时，主要更改的超参数是batch_size和num_hidden_layers，附录中的结果是我们尝试的几组参数中最好的结果，Beauty(batch_size=1024,num_hidden_layers=4)，Sports(batch_size=1024,num_hidden_layers=4)，Toys(batch_size=512,num_hidden_layers=4)，Yelp(batch_size=1024,num_hidden_layers=8)
你也可以尝试增加batch size以及隐藏层数来尝试获得更好的效果
希望我的回答对您有所帮助
