### ISSUE TITLE
Questions about the full-sort setting

### ISSUE THREAD

**Issue by Ethan00Si** [Woeee/FMLP-Rec#4]
Hi there!

Very glad to see your interesting work! It's novel and effective.

Sadly, I have an issue about the 'full_sort' setting for evaluation. The code in this [line](https://github.com/Woeee/FMLP-Rec/blob/51acc8cf20e08e0480ea2cf2f047709436775119/trainers.py#L200) shows that you have filtered the users' historically interacted items in the full item table and then calculate the metrics based on the filtered items. What confused me is  that, in the e-commerce scenario, many users will have repeated consumption behaviors. The next interacrted item is prone to be an item interacted before. And many of your experiments are conducted on the e-commerce datasets, e.g., the Amazon dataset.  So my question is that **is it reasonable to filter out the historically interacted items before evaluation in the full-sort setting**. Morever, could you please **provide any references for the full-item setting**? I don't see references in the paper.

Anyhow, the experiments in full-sort setting do not badly affect the robustness of your paper. I just want to know why you have filltered out the interacted items.

Thanks in advance!

**Comment by Ethan00Si** [comment]
If you can respond to my issue and dispel my confusion, I shall be immensely grateful. @Woeee

**Comment by Woeee** [comment]
I'm sorry for the delay in responding. Our work is based on the development of S3-rec, and we have ported relevant evaluation modules. 
Regarding the full-sort module, it's based on the work of previous researchers, and it's certain that the already appeared items need to be removed because they have already expressed the user's preferences. You can get the results you want from this [answer.](https://github.com/RUCAIBox/RecBole/issues/1550#issuecomment-1321918958)
I hope it‘s helpful to you. If you have any other questions, please feel free to contact me.

**Comment by Ethan00Si** [comment]
Thank you for your response. I have seen the source codes of the S3-Rec paper regarding the full-sort setting, but I remain skeptical of this setting. This is because certain evaluation metrics for some test samples will inevitably be zero, as the positive samples involve repeated consumption behaviors, and the predicted value of these positive samples will be filtered out. This will result in an average evaluation metric that is lower than the actual results. Furthermore, the original S3-Rec did not provide experimental results for the full-sort setting in the published paper, nor did it provide reference papers for this setting that filters out interactions. Therefore, **I am curious to know if there are any papers that explicitly use this setting in their experimental setup.** Additionally, for several representative retrieval models, their open source code is evaluated in the full-sort setting, but they do not filter out interacted items, such as ComiRec and Re4. Here are links for their codes, [Re4](https://github.com/DeerSheep0314/Re4-Learning-to-Re-contrast-Re-attend-Re-construct-for-Multi-interest-Recommendation/tree/main) and [ComiRec](https://github.com/THUDM/ComiRec/tree/master). That is why I don't think this experimental setting to be widely accepted.
