### ISSUE TITLE
代码里面没看着fft，滤波器等逻辑了，请问是上传的代码没包括这一部分吗，谢谢

### ISSUE THREAD

**Issue by mathetian** [Woeee/FMLP-Rec#5]

**Comment by Woeee** [comment]
你可以参考modules.py的[116](https://github.com/Woeee/FMLP-Rec/blob/51acc8cf20e08e0480ea2cf2f047709436775119/modules.py#L116)到[119](https://github.com/Woeee/FMLP-Rec/blob/51acc8cf20e08e0480ea2cf2f047709436775119/modules.py#L119)行
