### ISSUE TITLE
session-based结果复现

### ISSUE THREAD

**Issue by HowardZJU** [Woeee/FMLP-Rec#6]
您好~这是一份很健壮的基线。这段时间我们对您的工作进行了深入研究和改进，目前在其他数据上取得了一定的提升；但是在session-based recommendation上和论文中的报道结果还有较大差距。

我们观察到您可能为每个数据集分别配置了不同的超参数（例如在full-sort评测协议下）。可以请教一下您四个session-based数据集上，fmlp的超参数设置和随机种子设置吗？如果是多个随机种子平均的话，分别是哪些随机种子呢？

**Comment by Woeee** [comment]
我们没有更改随机种子，session-based 数据集上的超参数也是根据我们的计算条件所尝试的，如果你的GPU显存足够大的话可以尝试用更大的 batch_size 和 num_hidden_layers 提升模型的表现。
具体的超参数如下：
nowplaying(batch_size=256, num_hidden_layers=4)
retailrocket(batch_size=1024, num_hidden_layers=2)
tmall(batch_size=1024, num_hidden_layers=8)
yoochoose(batch_size=4096, num_hidden_layers=2)

**Comment by HowardZJU** [comment]
感谢您的回复。我们之前没有调节batchsize和number-of-layers，导致很难在多个seed下在会话数据上取得置信提升。您的回复让我们有了下一步迭代的基准。

再次感谢您的反馈！
