### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Lyz103** [Woeee/FMLP-Rec#7]
请问能否提供消融实验部分的代码？谢谢！

**Comment by Woeee** [comment]
你把需要消融的部分注释掉就行了

**Comment by Lyz103** [comment]
抱歉，应该是不同的滤波方式的代码。谢谢！
<img width="484" alt="058cd69c5711a7f5b3085317285d535" src="https://github.com/user-attachments/assets/11906077-7d38-43dd-b801-c3a73fc14ade">

**Comment by Woeee** [comment]
根据filter layer的size自己设置固定参数的filter然后替换，前1/2为1后1/2为0是低通，前1/2为0后1/2为1是高通，中间1/3为0是带阻

**Comment by Lyz103** [comment]
好的好的，谢谢！

**Comment by Lyz103** [comment]
beauty的SASRec加filter的结果复现不出来，能解释一下三个filter代码具体怎么写的吗？万分感谢！！
<img width="744" alt="55372d904ed76d3733cb64589ff9979" src="https://github.com/user-attachments/assets/f30be338-0d77-4636-8659-27f0d5369fc8">
